### ISSUE TITLE
Capturing a King

### ISSUE THREAD

**Issue by aphyer** [dylan/gameofcyvasse#2]
Just to be clear:  the rules state that "All pieces can kill a piece of their same type or lower, and the one above it. The list below has the weakest pieces at the top progressing to the strongest."  The King is at the bottom of the list, making it the strongest piece, capable of killing any unit.  Does this mean that the only piece capable of capturing my King is my opponent's Dragon; in other words, that if I can kill his Dragon my King is invincible?  That feels somewhat strange.  Or are Kings exempt from the usual rules of strength?

**Comment by dylan** [comment]
I hope this works. :D Thoughts?

**Comment by aphyer** [comment]
Yes, that looks an awful lot better.  Thanks!
