### ISSUE TITLE
Rules, website comments

### ISSUE THREAD

**Issue by embergrave** [dylan/gameofcyvasse#3]
I commend you for creating a rule set that I actually agreed with. However I would really like to work with you on creating an even deeper rule set. While you presented a good base with the tiles, the units, etc. a lot was left out. I did some of the more basic stuff here, but a lot of it needs to be hashed out further. I made a really nice version of your board so I could play with friends. Also if you wanted help on your website I design for a living and would love to help it to be less bland.

My Cyvasse Board: http://imgur.com/a/PqKEg

Vulnerability: An area behind a unit in which it is vulnerable from the attacks of any other unit in the game.

When I said "1 direction" or "3 directions" I mean 1 direction would be the one straight ahead or behind, 3 would be the one straight ahead or behind plus the 2 on each side of it (diagonally)

There are 2 types of victories: King Slayer, and King Humiliation. King slayer is simply killing the king, however if you can block the king from moving it's considered king humiliation is makes victory that much sweeter. 

General --------

Turning a unit to face another direction takes up 1 of the units movements
When fortress tile is "ruined" the tile must be flipped until next game.
Attacking an enemy unit or fortress uses all movements.
No more then 2 mountains can be placed in a row (both vertically and horizontally), and no more then 3 mountains may be touching.

Pieces ---------

Dragon
Pieces: 1
Movement: 3, Any direction
Attack: Front 7 Directions, 1 Space, Cannot attack units on forest tile
Vulnerability: Behind 1 Direction
Kill: All
Die: Crossbowmen, Catapult, Dragon, King

King
Pieces: 1
Movement: 1
Attack: Front 5 Directions, 1 Space
Vulnerability: Behind 1 Direction
Kill: All
Die: All

Trebuchet
Pieces: 1
Movement: 1
Attack: Front 1 Direction, 3 Spaces
Vulnerability: Behind 5 Directions
Kill: All
Die: King, Dragon, Trebuchet, Catapult

Catapult
Pieces: 1
Movement: 1
Attack: Front 5 Directions, 2 Spaces
Vulnerability: Behind 3 Directions
Kill: All
Die: King, Dragon, Trebuchet, Catapult, Elephant

Elephant
Pieces: 2
Movement: 1
Attack: Front 5 Directions, 1 Space
Vulnerability: Behind 1 Direction
Kill: King, Catapult, Heavy Horse, Light Horse, Crossbowmen, Spearmen, Rabble, Elephant
Die: King, Dragon, Trebuchet, Catapult, Elephant, Heavy Horse

Heavy Horse
Pieces: 2
Movement: 2
Attack: Front 3 Directions, 1 Space
Vulnerability: Behind 1 Direction
Kill: King, Elephant, Heavy Horse, Light Horse, Crossbowmen, Spearmen, Rabble, Heavy Horse
Die: King, Dragon, Trebuchet, Catapult, Elephant, Heavy Horse, Light Horse, Heavy Horse

Light Horse
Pieces: 3
Movement: 3
Attack: Front 3 Directions, 1 Space
Vulnerability: Behind 3 Directions
Kill: King, Heavy Horse, Light Horse, Crossbowmen, Spearmen, Rabble, Light Horse
Die: King, Dragon, Trebuchet, Catapult, Elephant, Heavy Horse, Light Horse, Crossbowmen, Light Horse

Crossbowmen
Pieces: 4
Movement: 1
Attack: Front 7 Directions, 1 Spaces
Vulnerability: Behind 3 Direction
Kill: King, Dragon, Light Horse, Crossbowmen, Spearmen, Rabble, Crossbowmen
Die: King, Dragon, Light Horse, Heavy Horse, Elephant, Trebuchet, Catapult, Crossbowmen

Spearmen
Pieces: 5
Movement: 1
Attack: Front 3 Directions, 1 Space
Vulnerability: Behind 3 Direction
Kill: King, Crossbowmen, Rabble, Heavy Horse, Light Horse, Spearmen
Die: King, Dragon, Elephant, Trebuchet, Catapult, Crossbowmen, Spearmen

Rabble
Pieces: 6
Movement: 1
Attack: Front 3 Directions, 1 Space
Vulnerability: All Directions
Kill: Spearmen, Rabble, King
Die: All

Tiles ---------

Grass (Light Green) x14
Movement: No effects on any units
Attack: No effects on any units

Forest (Dark Green) x6
Movement: Takes 1 movement from all units with the exception of the dragon.
Attack: Reduces the range of all units to 1, Dragons cannot attack units on forest tiles, Vulnerability of units on forest tiles increase by 2 directions from the rear.

Water (Blue) x5
Movement: Takes all movement from all units with the exception of the dragon. Dragons can not land on water tiles. Movement regained next turn, and is not effected again until the water tile is reentered.
Attack: Melee units occupying a water tile cannot attack enemy units on connected water tiles. Reduces vulnerability of all units to 0 (as they could see enemies coming on open water).

Mountain (Red) x6
Movement: Cannot be passed through by all units with the exception of the dragon. Dragons can land on mountains. If landed on by a dragon, reduces movements to 0 until next turn.
Attack: Acts as a wall, no unit can attack units on the opposing side of the tile. Ranged units can attack dragons on mountains.

Fortress (White) x1
Movement: Enemy units cannot enter fortress tile until it is "ruined".
Attack: Shields any unit within it from any opposing unit for 1 attack. After the attack the fortress tile is flipped and the unit becomes vulnerable to attack. Enemy units can attack an empty fortress tile.

**Comment by embergrave** [comment]
I tried a game last night an there were far to many pieces. Plus at the start of the game it was rather a terrible slaughter as I put all my powerful units in the front and he put his rabble in the front which led to him literally not being able to move any pieces. I feel an 8 by 8 board is to small, a 10 x 10 board would be much better for a game like cyvasse.

**Comment by AnthonyAppleyard** [comment]
To play on a ready-made squared board:-
(8x8): on a chessboard
(9x9): on a chessboard that has a margin: put the pieces at the corners of the squares
(10x10): on a chessboard that has a margin: use the margin as an extra 36 squares placed all round.]
