### ISSUE TITLE
Add Flanking

### ISSUE THREAD

**Issue by xorn** [dylan/gameofcyvasse#4]
I like the idea of flanking from this write up:

http://asoiaf.westeros.org/index.php/topic/58545-complete-cyvasse-rules/

**Comment by dylan** [comment]
My concern with adding flanking is that tactically you can flank in chess (which is what I was trying to emulate) without adding any additional arithmetic etc. to the rules.

I always tried to err on the side of simplicity/clarity, and think hard about what sort of games could/would be played during medieval times, where this other ruleset took one word from the passage and extrapolates loads of rules and complexities from it.

**Comment by xorn** [comment]
I agree with simplicity. The rule set from the link I provided gets too math heavy and ends up more like D&D. 
Thank you for providing these rules, they are awesome!

**Comment by dylan** [comment]
My pleasure! I'm glad you enjoy them. :D
