### ISSUE TITLE
Turn Rules

### ISSUE THREAD

**Issue by charlierudolph** [dylan/gameofcyvasse#5]
I'm just wondering what exactly you define as a turn.

Chess and Stratego both define a turn as moving a single piece.
Blitzkrieg however allows you to move all your pieces at once. (As far as I know. Never actually played just looking up the rules.)

**Comment by dylan** [comment]
Good catch, due to the limited number of pieces I consider moving one piece a turn.

**Comment by dylan** [comment]
It might be worth trying both variations to see which plays better. Any thoughts?

**Comment by dylan** [comment]
Closes due to the line of thinking, this is a small-ish board. All the pieces moving would make for quite a fast game...
