### ISSUE TITLE
Unit power & number

### ISSUE THREAD

**Issue by govlax17** [dylan/gameofcyvasse#6]
Hey this looks great. I just have some suggestions regarding units:

First: you should get more than one of each unit at the start. The books do mention haing multiple of some units. This would also make the game more dynamic and complex as is suggested by the series. To accommodate this, maybe make the board bigger? Here is the unit numbering I would suggest:

5 rabble
4 spearmen
4 crossbows
3 light horse
2 heavy horse
2 elephants
2 trebuchets
2 catapults
1 dragon 
1 king

So 26 pieces; I'd make the board 14x14 (196 squares) to maintain the same piece to square ratio (around 1/7). Also you might want to increase the number of tiles to fit the bigger board. Note: is a player allowed to box his king up behind walls?
Also what Are the rules regarding diagonal movement?

Second: the pieces should be more variable in their ability. Here I suggest possible attributes:

Rabble: 1 space movement. Cannot attack heavy horse, dragon, elephant

Spears: 1 space movement. Cannot attack dragon. Connot be attacked by lc or hc.

Crossbows: 1 space movement. 1 space range (can move and attack in same turn). Gets one space range bonus when on wall or fortress tile. Does not have range attack in forest. Can meelee attack but can only kill rabble.

Lc: 3 space movement. Cannot attack dragon or spears. 

Hc: 2 space movement. Cannot attack dragon or spears. Charge (may attack two rows in the same direction)... But not able in forest.

Elephant: 2 space movement. Cannot attack dragon. If dragon attacks in one square radius, elephant will retreat automatically in opposite direction up to 2 spaces. Charge: can attack two squares in one direction. (Not in forest)

Catapult: one space movement. Two space range. 

Trebuchet: one space movement. Three space range. May destroy fortress and wall. (Note: only dragons or trebuchets can destroy fortress and wall.)

Dragon: unlimited moves. Can destroy walls. Can destroy forest and fortress (but has to destroy forest or fortress before it can kill unit in forest square.

King: one space movement. Gives each of friendly units in one square radius one extra range.

**Comment by dylan** [comment]
So when I put this together I was trying to go for as simple as possible while still playable. Considering the times in the book the fewer the pieces the better, and we already start with a disadvantage in that area due to the board itself being made up of pieces.
