### ISSUE TITLE
Design of hexagonal tiles I've made

### ISSUE THREAD

**Issue by Fotkurz** [dylan/gameofcyvasse#7]
Here is the design of some hexagonal tiles I've made 

https://www.dropbox.com/s/2llfuuzjmw7sm7q/cyvasse.jpg

I used this site http://www.gameofthronesbr.com/2012/10/como-jogar-cyvasse_5687.html image as base.

Is it possible to play with those hexagonal style pieces?
I never played it before :/, but I really like the game of thrones books and I remember some part in A Feast For Crows or A Dance with Dragons, where Arianne explains how the game looks like, or was the Imp who explained? Can't remember too but you got what I mean, enjoy! 
I am printing and sculpting some wood pieces for myself.

**Comment by dylan** [comment]
Thanks for sharing!

http://skitzinc.wikispaces.com/Cyvasse#toc16 Is the best list of Cyvasse quotes I've seen. It mentions 'squares' there but as long as it's fun, who's to judge? :) I hope you find the rules fun.
