### ISSUE TITLE
Unbeatable board setups

### ISSUE THREAD

**Issue by jf1x** [dylan/gameofcyvasse#8]
Hi there,

I found your ruleset a few days ago and have been testing out some board combinations.

I've attached an image that demonstrates a valid board setup according to your rules. It depicts the right half of the player's half of the board.

![king](https://f.cloud.github.com/assets/277449/1529983/aa6fd736-4c42-11e3-9dad-f995b5fdaa16.PNG)

Light green tiles are grass, dark green are forests, orange are mountains, and blue is water. The "K" symbol signifies the King.
1. Can you confirm this is a valid board setup according to the rules?
2. Is this a situation that is unwinnable by the opposition?
- The King is in Forest, meaning the opposing Dragon cannot attack it.
- It is surrounded by Mountains, meaning Melee units cannot cross to attack it, nor can ranged units fire over them.

If the setup is unwinnable, how do you think the rules could be amended to prevent such situations? Currently the rules about Mountain tiles state:

> Players may not exceed two mountains per row. This prevents mountains from being build into impassible walls.

Perhaps this needs to be amended to state that no area can be enclosed by mountain tiles?

**Comment by dylan** [comment]
Great catch!

We could say:

> Players may not have more than two contiguous mountains. This prevents mountains from being build into impassible walls.

This would allow for nice diagonals, short rows, but always passable?

**Comment by dylan** [comment]
This also makes me wonder what the strategy for cracking open a placement like this would be:

```
MMWW
FFFW
MMWW
```

**Comment by alexeykoren** [comment]
This one may be broken using trebuchet near water on second line I guess

Catapult on a top or bottom of second column will work as well

**Comment by alexeykoren** [comment]
maybe there should be just a rule that no cell should be isolated from
other? in this case any unit (including melee) can win the game in most
cases

**Comment by jf1x** [comment]
> Players may not have more than two contiguous mountains. This prevents mountains from being build into impassible walls.

I think this might be the way to go. This would not allow the board setup I originally posted, meaning melee can enter and ranged can attack.

Even if both players place mountain tiles at the top of their respective sides (meaning technically there are more than 2 contiguous mountains on the full board) there should still not be a way for a unit to be blocked in.

> maybe there should be just a rule that no cell should be isolated from
> other?

Yeah I agree, and I think the update to the rule mentioned earlier would prevent this from happening - I can't think of any situation off the top of my head that would allow a cell to be isolated when following it.

**Comment by alexeykoren** [comment]
What about mixing  mountains and water to build impassible wall?

wmwm
ppppw
kppm

king is in the left-bottom corner in a forest, surrounded by mountains and
water

is it valid?

**Comment by dylan** [comment]
Water is passable, it just halts movement for a turn, so units can cover the tile or the unit in the water in case the king attacks. So it’s viable/legal unless I’m not getting the question?

**Comment by alexeykoren** [comment]
Yeah, you right. I just forget the water rule. I discard my comment :)

Im a little bit of a software developer so I may write some sort of a
simulation engine for the game.

Btw, are you guys interested in launching facebook + mobile Cyvasse apps?
It should be relatively easy, especially for a bunch of people?

Im a big fan of GoT and board games so Im thinking of it just for fun, at
least for a start.

**Comment by dylan** [comment]
May be fun, DM me on twitter @dylanrw and we can go from there. :)

**Comment by alexeykoren** [comment]
I dont use twitter )
ping me on fb: https://www.facebook.com/alexey.koren  )
